versions.v1 = {
  name: "Autumn",
  version: "v1",
  date: "2025",
  folder: "asset-v1/",
  looptime: 10667,
  bpm: 90,
  totalframe: 512,
  nbpolo: 7,
  bonusloopA: true,
  bonusendloopA: false,
  colBck: "#2D1503",
  col0: "#DC7328",
  col1: "#D0893E",
  col2: "#633F18",
  col3: "#52320F",
  col4: "#321B03",
  animearray: [
    {
      name: "1_ponkat",
      color: "E7AC36",
      uniqsnd: !0,
    },
    {
      name: "2_puh",
      color: "E7AC36",
      uniqsnd: !0,
    },
    {
      name: "3_kah",
      color: "E7AC36",
      uniqsnd: !0,
    },
    {
      name: "4_shaka",
      color: "E7AC36",
      uniqsnd: !0,
    },
    {
      name: "5_puiteefiti",
      color: "E7AC36",
      uniqsnd: !0,
    },
    {
      name: "6_lewis",
      color: "412900",
      uniqsnd: !1,
    },
    {
      name: "7_parabaum",
      color: "412900",
      uniqsnd: !0,
    },
    {
      name: "8_ohoh",
      color: "412900",
      uniqsnd: !0,
    },
    {
      name: "9_papapah",
      color: "412900",
      uniqsnd: !0,
    },
    {
      name: "10_prraprra",
      color: "412900",
      uniqsnd: !0,
    },
    {
      name: "11_tanana",
      color: "75760B",
      uniqsnd: !0,
    },
    {
      name: "12_trumpe",
      color: "75760B",
      uniqsnd: !0,
    },
    {
      name: "13_pampam",
      color: "75760B",
      uniqsnd: !0,
    },
    {
      name: "14_pounoun",
      color: "75760B",
      uniqsnd: !0,
    },
    {
      name: "15_whistle",
      color: "75760B",
      uniqsnd: !1,
    },
    {
      name: "16_ohwoah",
      color: "801E16",
      uniqsnd: !0,
    },
    {
      name: "17_ilike",
      color: "801E16",
      uniqsnd: !1,
    },
    {
      name: "18_tom",
      color: "801E16",
      uniqsnd: !1,
    },
    {
      name: "19_sam",
      color: "801E16",
      uniqsnd: !1,
    },
    {
      name: "20_time",
      color: "801E16",
      uniqsnd: !0,
    },
  ],
  bonusarray: [
    {
      name: "Stay",
      src: "b1-v1-stay-hb",
      code: "1,2,7,11,17",
      sound: "bonus-stay",
      aspire: "aspire-stay",
      loop: 2,
    },
  ],
};